name: Deploy para GitHub Pages

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest
permissions:
contents: read
pages: write
id-token: write

steps:
- name: Checkout do código
uses: actions/checkout@v3

- name: Configurar GitHub Pages
uses: actions/configure-pages@v3

- name: Upload dos arquivos
uses: actions/upload-pages-artifact@v2
with:
path: '.'

- name: Publicar no GitHub Pages
uses: actions/deploy-pages@v2